# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

- name: ftp
  config:
    root: "/opt/dionaea/var/lib/dionaea/ftp/root"
    response_messages:
      welcome_msg: DiskStation 220 FTP server ready.
